spring:
  datasource:
    account:
      url: jdbc:h2:mem:account
      username: sa
      password:

    chat:
      url: jdbc:h2:mem:chat
      username: sa
      password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

