spring:
  datasource:
    account:
      url: jdbc:mysql://localhost:3307/account
      username: root
      password: 1234

    chat:
      url: jdbc:mysql://localhost:3307/chatdb
      username: root
      password: 1234

  jpa:
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8080
